# Generated by Django 6.0.7 on 2026-07-14 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('tipo', models.CharField(choices=[('jogo', 'Jogo'), ('filme', 'Filme'), ('livro', 'Livro')], max_length=10, verbose_name='tipo')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('criador', models.CharField(blank=True, max_length=200, verbose_name='criador')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('capa', models.ImageField(blank=True, upload_to='capas/', verbose_name='capa')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL, verbose_name='cadastrado por')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'itens',
                'ordering': ('titulo',),
            },
        ),
    ]
